### YamlMime:Certification
title: 'MCSE: Business Applications'
metadata:
  title: 'MCSE: Business Applications'
  description: 'MCSE: Business Applications'
uid: certification.mcse-business-applications
iconUrl: /media/learn/certification/badges/mcse-badge.svg
summary: |-
  <div>
  <div><strong>Diese Zertifizierung endet am 31. Januar 2021. Nach diesem Datum können Sie diese Zertifizierung nicht mehr erhalten. Alle Zertifizierungen, die Sie vor deren Ablaufen erhalten haben, werden weiterhin auf Ihrem Transkript im <a href='https://www.microsoft.com/learning/dashboard.aspx'>Zertifizierungs-Dashboard</a> angezeigt. Sie können auch <a href='/learn/certifications/retired-certifications'>alle abgelaufenen Zertifizierungen durchsuchen</a>.</strong><br/><br/></div>
  </div>

  Diese Zertifizierung bestätigt, dass Sie das Know-how haben, um mit Microsoft Dynamics 365 Technologien zu arbeiten und zu verwalten. Sie beginnen mit einer Grundlage in Microsoft Dynamics 365 und zeigen zusätzliche Expertise in einem oder mehreren geschäftsspezifischen Bereichen.

  Um die MCSA&#58; Zertifizierung für Unternehmen zu erhalten, müssen Sie die folgenden Anforderungen erfüllen&#58;
  - Verdienen Sie die vorausgesetzte Zertifizierung&#58; [MCSA&#58; Microsoft Dynamics 365 für den Betrieb](/learn/certifications/mcsa-microsoft-dynamics-365-for-operations)
  - Und absolvieren Sie eine der Wahlprüfungen&#58;
    - [MB2-716&#58; Microsoft Dynamics 365 Customization and Configuration](/learn/certifications/exams/mb2-716)
    - [MB6-897&#58; Microsoft Dynamics 365 for Retail](/learn/certifications/exams/mb6-897)
    - [MB6-898&#58; Microsoft Dynamics 365 for Talent](/learn/certifications/exams/mb6-898)
subTitle: Diese Zertifizierung bestätigt, dass Sie das Know-how haben, um mit Microsoft Dynamics 365 Technologien zu arbeiten und zu verwalten. Sie beginnen mit einer Grundlage in Microsoft Dynamics 365 und zeigen zusätzliche Expertise in einem oder mehreren geschäftsspezifischen Bereichen.
levels:
- beginner
skills:
- none
roles:
- business-analyst
type: mcse
products:
- dynamics
exams:
- uid: exam.mb-2-716
- uid: exam.mb-6-897
- uid: exam.mb-6-898
prerequisites:
- uid: certification.mcsa-microsoft-dynamics-365-for-operations
  isOptional: false
resources:
- title: Schulungs- und Zertifizierungsleitfaden
  description: Informieren Sie sich über die Zertifizierungen in einem übersichtlichen Schulungs- und Zertifizierungsleitfaden.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: Zertifizierungsposter
  description: Verschaffen Sie sich einen Überblick über die Grundlagen, aufgabenbasierte und fachliche Zertifizierungen.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: Exam Replay
  description: Sehen Sie sich zwei großartige Angebote an, die Ihnen helfen, Ihre Erfolgschancen zu erhöhen.
  href: deals.md
- title: Unterstützung von Zertifizierungen
  description: Erhalten Sie Hilfe in Microsoft Certification Support-Foren. Ein Forenmoderator wird Ihnen an einem Werktag (Montag-Freitag) antworten.
  href: help.md
- title: Zertifizierungsdashboard
  description: Überprüfen und verwalten Sie Ihre geplanten Termine, Zertifikate und Transkripte.
  href: https://www.microsoft.com/learning/dashboard.aspx

